// Date: 4/14/2013 9:50:59 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer buffer;
  
  public ModelModel()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("buffer.bumper2", 31, 14);
    setTextureOffset("buffer.bumper1", 31, 14);
    setTextureOffset("buffer.baseSmall", 27, 1);
    setTextureOffset("buffer.baseBig", 1, 1);
    setTextureOffset("buffer.boardR1", 1, 16);
    setTextureOffset("buffer.boardR2", 1, 24);
    setTextureOffset("buffer.boardW", 15, 16);
    
    buffer = new ModelRenderer(this, "buffer");
    buffer.setRotationPoint(0F, 0F, 0F);
    setRotation(buffer, 0F, 0F, 0F);
    buffer.mirror = true;
      buffer.addBox("bumper2", 3F, -1F, -5F, 2, 2, 1);
      buffer.addBox("bumper1", -5F, -1F, -5F, 2, 2, 1);
      buffer.addBox("baseSmall", -3F, -8F, 1F, 6, 7, 4);
      buffer.addBox("baseBig", -4F, -8F, -3F, 8, 9, 4);
      buffer.addBox("boardR1", -6F, -2F, -4F, 4, 4, 2);
      buffer.addBox("boardR2", 2F, -2F, -4F, 4, 4, 2);
      buffer.addBox("boardW", -2F, -2F, -4F, 4, 4, 2);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    buffer.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
