// Date: 12/19/2013 4:57:46 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer loco;
  
  public ModelNew()
  {
    textureWidth = 128;
    textureHeight = 64;
    setTextureOffset("loco.wheels", 1, 23);
    setTextureOffset("loco.frame", 1, 1);
    setTextureOffset("loco.boiler", 68, 38);
    setTextureOffset("loco.cab", 81, 8);
    setTextureOffset("loco.cowcatcher", 1, 43);
    setTextureOffset("loco.stack", 47, 43);
    setTextureOffset("loco.dome", 21, 43);
    setTextureOffset("loco.jar1", 28, 52);
    setTextureOffset("loco.jar2", 28, 52);
    setTextureOffset("loco.jar3", 28, 52);
    setTextureOffset("loco.jar4", 28, 52);
    setTextureOffset("loco.pipe1", 45, 53);
    setTextureOffset("loco.pipe2", 45, 53);
    setTextureOffset("loco.pipe3", 45, 53);
    setTextureOffset("loco.pipe4", 45, 53);
    
    loco = new ModelRenderer(this, "loco");
    loco.setRotationPoint(0F, 0F, 0F);
    setRotation(loco, 0F, 0F, 0F);
    loco.mirror = true;
      loco.addBox("wheels", -20F, -5F, -16F, 23, 2, 16);
      loco.addBox("frame", -21F, -7F, -17F, 25, 2, 18);
      loco.addBox("boiler", -20F, -17F, -14F, 16, 10, 12);
      loco.addBox("cab", -4F, -19F, -16F, 7, 12, 16);
      loco.addBox("cowcatcher", -22F, -8F, -13F, 3, 5, 10);
      loco.addBox("stack", -17F, -22F, -10F, 4, 5, 4);
      loco.addBox("dome", -11F, -19F, -11F, 6, 2, 6);
      loco.addBox("jar1", -10F, -13F, -4F, 4, 6, 4);
      loco.addBox("jar2", -10F, -13F, -16F, 4, 6, 4);
      loco.addBox("jar3", -15F, -13F, -4F, 4, 6, 4);
      loco.addBox("jar4", -15F, -13F, -16F, 4, 6, 4);
      loco.addBox("pipe1", -9F, -16F, -3F, 2, 3, 2);
      loco.addBox("pipe2", -9F, -16F, -15F, 2, 3, 2);
      loco.addBox("pipe3", -14F, -16F, -3F, 2, 3, 2);
      loco.addBox("pipe4", -14F, -16F, -15F, 2, 3, 2);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    loco.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
