// Date: 12/6/2012 9:47:44 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer loco;
  
  public ModelNew()
  {
    textureWidth = 128;
    textureHeight = 64;
    setTextureOffset("loco.wheels", 1, 23);
    setTextureOffset("loco.frame", 1, 1);
    setTextureOffset("loco.boiler", 67, 38);
    setTextureOffset("loco.cab", 81, 8);
    setTextureOffset("loco.cowcatcher", 1, 43);
    setTextureOffset("loco.stack", 49, 43);
    setTextureOffset("loco.dome", 23, 43);
    
    loco = new ModelRenderer(this, "loco");
    loco.setRotationPoint(0F, 0F, 0F);
    setRotation(loco, 0F, 0F, 0F);
    loco.mirror = true;
      loco.addBox("wheels", -20F, -5F, -16F, 23, 2, 16);
      loco.addBox("frame", -21F, -7F, -17F, 25, 2, 18);
      loco.addBox("boiler", -20F, -18F, -15F, 16, 11, 14);
      loco.addBox("cab", -4F, -19F, -16F, 7, 12, 16);
      loco.addBox("cowcatcher", -22F, -8F, -14F, 3, 5, 12);
      loco.addBox("stack", -17F, -24F, -10F, 4, 6, 4);
      loco.addBox("dome", -11F, -20F, -11F, 6, 2, 6);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    loco.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
