@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mods.railcraft.common.advancements.criterion;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;